### ISSUE TITLE
Inconsistent emojis and emoji dropdown not showing in chat

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/forums.openusercss.org#16] opened 2018-05-05 08:44 UTC
So... why exactly are there to kinds of emojis again? I would rather not take the blobs.

![image](https://user-images.githubusercontent.com/19552720/39661393-87442a76-5059-11e8-9443-41c90c12304d.png)

Yeah also if I type `:p` in the forum it works and shows stuff like `:pig:` and such but in the chat it doesn't.

**Comment by DecentM** [comment] 2018-05-07 02:42
I can't seem to be able to reproduce this, when I type colon and then `t` for example, the dropdown immediately shows up.  
I'm not sure, but can you test to see if a browser extension might cause this?

**Comment by RaitaroH** [comment] 2018-05-07 03:11
Nevermind the dropdown, it seems it works again o.O

But srsly the emojis.

**Comment by DecentM** [comment] 2018-05-07 09:58
I'm not sure which emoji pack was installed before, but it looks like multiple ones are active at the same time. I'll take a look how that happened in the next maintenance window.

**Comment by DecentM** [comment] 2018-06-03 21:20
I attempted a fix for this, let me know if it still doesn't work!

**Closed by DecentM** 2018-06-03 21:20 UTC
Labels: waiting for maintenance
